highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
gems:
  - jekyll-sitemap
permalink: blogs/:title/
title: solving the x's and y's of math, programming and life
email: gauravdhingra.gxyd@gmail.com
description: Website of Gaurav Dhingra, Applied Mathematics student at IIT Roorkee
keywords: gaurav, dhingra, iit, roorkee, developer, sympy, geek, programmer, pianist, github, linux
baseurl: ""
url: https://gxyd.github.io
name: Gaurav Dhingra's blog
author:
  name: Gaurav Dhingra
  email: gauravdhingra.gxyd@gmail.com
